/*
 * This file is generated by jOOQ.
 */
package innossh.jooq.spring.audit.example.db;


import innossh.jooq.spring.audit.example.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = innossh.jooq.spring.audit.example.db.tables.User.USER;
}
