/*
 * This file is generated by jOOQ.
 */
package innossh.jooq.spring.audit.example.db.tables.daos;


import innossh.jooq.spring.audit.example.db.codegen.Auditable;
import innossh.jooq.spring.audit.example.db.tables.User;
import innossh.jooq.spring.audit.example.db.tables.records.UserRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, innossh.jooq.spring.audit.example.db.tables.pojos.User, Long> implements Auditable {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, innossh.jooq.spring.audit.example.db.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, innossh.jooq.spring.audit.example.db.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(innossh.jooq.spring.audit.example.db.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<innossh.jooq.spring.audit.example.db.tables.pojos.User> fetchById(Long... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public innossh.jooq.spring.audit.example.db.tables.pojos.User fetchOneById(Long value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<innossh.jooq.spring.audit.example.db.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<innossh.jooq.spring.audit.example.db.tables.pojos.User> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(User.USER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<innossh.jooq.spring.audit.example.db.tables.pojos.User> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(User.USER.UPDATED_AT, values);
    }
}
